name: getData

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: read

jobs:
  generate-data:
    runs-on: ubuntu-latest

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      RENV_VERSION: "0.17.3"

    strategy:
      matrix:
        r-version: ["4.2.1"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2.4.0
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install cURL library
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: renv package cache
        id: cache-renv
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-${{ matrix.r-version }}-${{ hashFiles('**/renv.lock') }}

      # Use renv to manage package installation
      - name: Install and activate renv
        run: |
          install.packages("renv@${{ env.RENV_VERSION }}")
          renv::activate()
        shell: Rscript {0}

      # Will automatically look for renv.lock in the root of the project
      - name: Install dependencies
        run: renv::restore()
        shell: Rscript {0}

      - name: Generate data
        run: source("prepData.R")
        shell: Rscript {0}

#      - name: Check
#        run: |
#          install.packages(c("cli", "rcmdcheck"))
#          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
#        shell: Rscript {0}
